### PR TITLE
Fixed issue with cheerio types.

### LINKED ISSUE #44: "npm install" fails
Is there an issue building this? I have not used npm before. I've tried npm rebuild followed by npm install.

$ npm install

> kijiji-scraper@6.0.0 prepare D:\data\Dropbox\work\kijiji\kijiji-scraper
> npm run build

> kijiji-scraper@6.0.0 build D:\data\Dropbox\work\kijiji\kijiji-scraper
> tsc

lib/backends/api-scraper.ts:16:24 - error TS2339: Property 'attribs' does not exist on type 'Element'.
  Property 'attribs' does not exist on type 'TextElement'.

16     const type = (item.attribs.type || "").toLowerCase();
                          ~~~~~~~

lib/backends/api-scraper.ts:17:34 - error TS2339: Property 'attribs' does not exist on type 'Element'.
  Property 'attribs' does not exist on type 'TextElement'.

17     const localizedLabel = (item.attribs["localized-label"] || "").toLowerCase();
                                    ~~~~~~~

lib/backends/api-scraper.ts:60:26 - error TS2339: Property 'attribs' does not exist on type 'Element'.
  Property 'attribs' does not exist on type 'TextElement'.

60         const url = item.attribs.href;
                            ~~~~~~~

lib/backends/api-scraper.ts:69:27 - error TS2339: Property 'attribs' does not exist on type 'Element'.
  Property 'attribs' does not exist on type 'TextElement'.

69         const name = item.attribs.name;
                             ~~~~~~~

Found 4 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kijiji-scraper@6.0.0 build: `tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kijiji-scraper@6.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Peter-laptop\AppData\Roaming\npm-cache\_logs\2020-12-11T02_19_18_268Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kijiji-scraper@6.0.0 prepare: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kijiji-scraper@6.0.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Peter-laptop\AppData\Roaming\npm-cache\_logs\2020-12-11T02_19_18_322Z-debug.log

### PR DESCRIPTION
**Pull request by technoligest**
resolve #44

### CODE REVIEW

File: lib/backends/api-scraper.ts [hunk 1]
```diff
@@ -11,7 +11,14 @@ import { AdInfo } from "../scraper";
 const AD_ID_REGEX = /\/(\d+)$/;
 const API_ADS_ENDPOINT = "https://mingle.kijiji.ca/api/ads";
 
+function isCheerioTagElement(element: cheerio.Element): element is cheerio.TagElement {
+    return (element as cheerio.TagElement).attribs !== undefined;
```
Comment (mwpenny) [inline lib/backends/api-scraper.ts]: There's an easier way to check this that I think is cleaner:

```ts
element.type === "tag";
```

File: lib/backends/api-scraper.ts [hunk 2]
```diff
@@ -11,7 +11,14 @@ import { AdInfo } from "../scraper";
...
+}
+
 function castAttributeValue(item: cheerio.Element, value: string): boolean | number | Date | string {
+    if  (!isCheerioTagElement(item)) {
+        return false;
```
Comment (mwpenny) [inline lib/backends/api-scraper.ts]: The intent behind this function is to return the original value if it can't be parsed. Can you move

```ts
value = value.trim();
```

to the top of this function and just return `value` instead of `false` here?

File: lib/backends/api-scraper.ts [hunk 3]
```diff
@@ -57,6 +64,9 @@ export function scrapeAdElement(elem: cheerio.Element): AdInfo | null {
     info.date = new Date(dateElem.text());
 
     $("pic\\:picture pic\\:link[rel='normal']").each((_i, item) => {
+        if  (!isCheerioTagElement(item)) {
```
Comment (mwpenny) [inline lib/backends/api-scraper.ts]: Style: only one space after `if` please.

File: lib/backends/api-scraper.ts [hunk 4]
```diff
@@ -66,6 +76,9 @@ export function scrapeAdElement(elem: cheerio.Element): AdInfo | null {
 
 
     $("attr\\:attribute").each((_i, item) => {
+        if  (!isCheerioTagElement(item)) {
```
Comment (mwpenny) [inline lib/backends/api-scraper.ts]: Style: only one space after `if` please.

File: package.json [hunk 5]
```diff
@@ -18,7 +18,7 @@
     "jest": "^26.4.0",
     "rimraf": "^3.0.2",
     "ts-jest": "^26.3.0",
-    "typescript": "^4.0.2"
+    "typescript": "^4.1.2"
```
Comment (mwpenny) [inline package.json]: User-defined type guards aren't a new feature, so there's no need to update the TypeScript version. That's a decision I think requires more thought.

Comment (mwpenny) [reply package.json]: Also, please update the version of `@types/cheerio` to explicitly use the latest (0.22.23).

**Review by mwpenny — CHANGES_REQUESTED** [review]
Thanks for the quick fix! I just have a few comments.

File: lib/backends/api-scraper.ts [hunk 6]
```diff
@@ -12,17 +12,17 @@ const AD_ID_REGEX = /\/(\d+)$/;
 const API_ADS_ENDPOINT = "https://mingle.kijiji.ca/api/ads";
 
 function isCheerioTagElement(element: cheerio.Element): element is cheerio.TagElement {
-    return (element as cheerio.TagElement).attribs !== undefined;
+    return element.type !== 'text';
```
Comment (mwpenny) [inline lib/backends/api-scraper.ts]: Right now there are only 2 Cheerio element types (text and tag), but we don't know if that will change in the future. Rather than checking what it's _not_, you should check what it _is_. I.e., `element.type === "tag"`. Also, please use double quotes for consistency with the rest of the library.

**Review by mwpenny — CHANGES_REQUESTED** [review]
Just a few small things regarding your `isCheerioTagElement()` changes (see my comment).

Also, please don't commit `package-lock.json`. `kijiji-scraper` is a library, which means end-users don't consume it directly and `package-lock.json` will be ignored for them. In other words, it prevents upstream breaking changes from impacting _us_, but does nothing to prevent issues for users.

Checking it in therefore provides a false sense of security and could potentially allow breaking changes in dependencies to slip through the cracks when testing. So I would rather omit the file and test what users will actually receive when the library is installed. If there's a problem, I want the build break so that we're aware sooner, rather than masking the problem.

If this were an application and not a library, then a lockfile would make sense since it would actually protect users from breaking changes in dependencies.

File: lib/backends/api-scraper.ts (hunk 6 above)
Comment (technoligest) [reply lib/backends/api-scraper.ts]: LMAO Really sorry, made the change while in a meeting will push the fix in a min
